# 
baseurl = "http://levisegal-site-staging.s3-website-us-west-2.amazonaws.com"
DefaultContentLanguage = "en"
title = "Levi Segal Blog"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#googleAnalytics = "XXX"

[Params]
  subtitle = "A place for science and coding - trust me"
  logo = "img/avatar-icon.jpg"
  favicon = "img/favicon.ico"
  dateFormat = "January 2th, 2006"
  commit = false
  rss = true
  comments = true

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Levi Segal"
  github = "levisegal"
  twitter = "LawrenceSegal"
  linkedin = "lawrence-segal-24b4b264"
  spotify = "$_Lawrence"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3
